configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/algo724-algo724-release%2Fcadenza-lite-sdk-7bd9a8b0425d5c614974be0258557815dcf4ca01e4b43368cf9e02eeb46b13fe.yml
